/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    About: typeof import('./components/Portfolio/About.vue')['default']
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    Contact: typeof import('./components/Portfolio/Contact.vue')['default']
    CV: typeof import('./components/Portfolio/CV.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    Home: typeof import('./components/Portfolio/Home.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
